apiVersion: v1
kind: Service
metadata:
  name: backend
  namespace: backend
  labels:
    app: backend
spec:
  ports:
    - port: 3000
      targetPort: 3000
  selector:
    app: backend
  type: ClusterIP 