apiVersion: batch/v1
kind: CronJob
metadata:
  name: url-cleanup
  namespace: url-shortener
spec:
  schedule: "0 0 * * *"  # Run daily at midnight
  concurrencyPolicy: Forbid  # Don't run if previous job is still running
  successfulJobsHistoryLimit: 3  # Keep history of last 3 successful jobs
  failedJobsHistoryLimit: 1      # Keep history of last failed job
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: cleanup
            image: ${REGISTRY}/url-shortener-cleanup:latest
            env:
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: url-shortener-secrets
                  key: database-url
            - name: REDIS_URL
              valueFrom:
                secretKeyRef:
                  name: url-shortener-secrets
                  key: redis-url
            resources:
              requests:
                memory: "128Mi"
                cpu: "100m"
              limits:
                memory: "256Mi"
                cpu: "200m"
          restartPolicy: OnFailure 