apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: redis
  namespace: redis
spec:
  serviceName: redis
  replicas: 1
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
        - name: redis
          image: redis:7-alpine
          ports:
            - containerPort: 6379
          command:
            - redis-server
            - --maxmemory
            - $(REDIS_MAXMEMORY)
            - --maxmemory-policy
            - $(REDIS_MAXMEMORY_POLICY)
          env:
            - name: REDIS_MAXMEMORY
              valueFrom:
                configMapKeyRef:
                  name: redis-config
                  key: REDIS_MAXMEMORY
            - name: REDIS_MAXMEMORY_POLICY
              valueFrom:
                configMapKeyRef:
                  name: redis-config
                  key: REDIS_MAXMEMORY_POLICY
          volumeMounts:
            - name: redis-data
              mountPath: /data
  volumeClaimTemplates:
    - metadata:
        name: redis-data
      spec:
        accessModes: [ "ReadWriteOnce" ]
        resources:
          requests:
            storage: 1Gi 