apiVersion: v1
kind: Service
metadata:
  name: url-cleanup
  namespace: url-shortener
  labels:
    app: url-cleanup
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: url-cleanup
  type: ClusterIP 