apiVersion: v1
kind: ConfigMap
metadata:
  name: frontend-config
  namespace: frontend
data:
  NEXT_PUBLIC_API_URL: "http://backend.backend.svc.cluster.local:3000"
  # Add any other non-sensitive configuration here 